# Ex2 - Getting and Knowing your Data



### Step 1. Import the necessary libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

### Step 2. Import the dataset

In [4]:
pd.read_csv("C:/Users/Asus/OneDrive/Apps/Desktop/adv-python/pandas_data - pandas_data.csv")

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Assign it to a variable called chipo.

In [5]:
df = pd.read_csv("C:/Users/Asus/OneDrive/Apps/Desktop/adv-python/pandas_data - pandas_data.csv")
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 4. See the first 10 entries

In [6]:
df.head(10) # first 10
df.tail(10) #last 10

,order_id,quantity,item_name,choice_description,item_price
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,1831,1,Chips,NaN,$2.15
4614,1831,1,Bottled Water,NaN,$1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 5. What is the number of observations in the dataset?

In [7]:
df.shape
#(rows,column)
df.shape[0]  # no. of rows
df.shape[1]  # no. of columns

5

In [8]:
df.shape[0]

4622

### Step 6. What is the number of columns in the dataset?

In [9]:
df.shape[1]

5

### Step 7. Print the name of all the columns.

In [10]:
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [11]:
df.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [12]:
#   group by implement non-aggregate 
a = df.groupby("item_name").agg({"quantity":"sum"})
b = a.sort_values("quantity",ascending = False)[0:1]
b
# b.head(1)

              quantity
item_name
Chicken Bowl       761

### Step 10. For the most-ordered item, how many items were ordered?

In [13]:
#   group by implement non-aggregate 
a = df.groupby("item_name").agg({"quantity":"sum"})
b = a.sort_values("quantity",ascending = False)[0:1]
b
# b.head(1)
b["quantity"]

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

### Step 11. What was the most ordered item in the choice_description column?

In [14]:
a = df.groupby("choice_description").agg({"quantity":"sum"})
b = a.sort_values("quantity" , ascending = False)
b.head(1)

                    quantity
choice_description
[Diet Coke]              159

Step 12. How many items were orderd in total?

In [15]:
# df[["item_name", 'quantity"]]
# df[["item_name"]]

a = df.quantity.sum()
print(a)
b = df.order_id.count()
print(b)

4972
4622

### Step 13. Turn the item price into a float

In [16]:
# df.item_price.str.slice(1).astype("float")
#df["item_price"] = df.item_price.str.slice(1).astype("float")
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

#### Step 13.a. Check the item price type

In [22]:
df["item_price"].dtype

dtype('O')

#### Step 13.b. Check the item price type

### Step 14. How much was the revenue for the period in the dataset?

In [18]:
revenue = df["item_price"]*df["quantity"]
r = revenue.sum()
r

'$2.39$3.39$3.39$2.39$16.98$16.98$10.98$1.69$11.75$9.25$9.25$4.45$8.75$8.75$11.25$4.45$2.39$8.49$8.49$2.18$2.18$8.75$4.45$8.99$3.39$10.98$3.39$2.39$8.49$8.99$1.09$8.49$2.39$8.99$1.69$8.99$1.09$8.75$8.75$4.45$2.95$11.75$2.15$4.45$11.25$11.75$8.75$10.98$8.99$3.39$8.99$3.99$8.99$2.18$2.18$10.98$1.09$8.99$2.39$9.25$11.25$11.75$2.15$4.45$9.25$11.25$8.75$8.99$8.99$3.39$8.99$10.98$8.99$1.69$8.99$3.99$8.75$4.45$8.75$8.75$2.15$8.75$11.25$2.15$9.25$8.75$8.75$9.25$8.49$8.99$1.09$9.25$2.95$11.75$11.75$9.25$11.75$4.45$9.25$4.45$11.75$8.75$8.75$4.45$8.99$8.99$3.99$8.49$3.39$8.99$1.09$9.25$4.45$8.75$2.95$4.45$2.39$8.49$8.99$8.49$1.09$8.99$3.99$8.75$9.25$4.45$11.25$4.45$8.99$1.09$9.25$2.95$4.45$11.75$4.45$8.49$2.39$10.98$22.50$22.50$11.75$4.45$11.25$4.45$11.25$4.45$11.25$11.25$11.75$9.25$4.45$11.48$17.98$17.98$1.69$17.50$17.50$4.45$8.49$2.39$17.50$17.50$4.45$4.45$11.25$11.75$10.98$8.49$10.98$2.18$2.18$11.48$8.49$2.39$4.45$11.25$11.75$8.75$8.49$2.18$2.18$8.49$3.39$8.49$8.99$10.98$11.48$8.49$1.09$1.09$9.25$8.75$2.95$9.25$4.45$11.25$11.48$8.49$8.49$8.99$2.39$11.25$8.75$2.95$1.09$8.99$8.49$2.39$10.98$1.09$3.99$11.25$8.75$8.49$3.39$8.75$9.25$2.15$11.25$11.25$11.25$4.45$22.50$22.50$4.45$11.75$8.75$17.50$17.50$8.75$9.25$8.75$2.15$9.25$4.30$4.30$8.75$11.25$2.15$8.99$1.09$8.99$3.99$8.75$2.95$2.95$11.75$5.90$5.90$9.25$9.25$11.75$9.25$2.95$17.50$17.50$8.75$9.25$10.98$8.99$1.09$1.09$1.09$8.99$10.98$1.09$8.75$8.75$9.25$9.25$8.75$8.75$8.99$8.99$8.99$1.09$11.75$1.25$8.99$2.39$9.25$2.95$8.99$3.99$8.49$2.39$8.49$8.49$8.49$1.69$8.49$3.99$8.99$1.69$1.09$23.78$23.78$17.50$17.50$2.15$8.75$9.25$9.25$8.75$4.45$8.75$11.25$11.25$1.25$9.25$4.45$11.25$11.75$11.75$6.49$8.99$2.39$8.49$2.39$11.25$8.75$2.15$8.99$1.69$8.75$11.25$2.15$4.45$8.75$8.49$8.99$17.50$17.50$8.49$1.09$1.09$8.75$1.25$2.15$11.08$8.49$8.49$8.99$2.39$8.75$2.15$1.50$11.25$2.15$8.49$8.49$11.75$9.25$11.75$1.25$11.25$8.75$4.45$6.49$9.25$2.95$11.25$4.45$1.25$1.25$8.49$2.39$2.18$2.18$8.49$2.18$2.18$22.16$22.16$17.50$17.50$8.75$2.95$6.49$8.99$3.39$3.39$8.99$8.49$11.25$2.15$11.25$2.95$11.25$1.25$8.99$1.09$8.75$8.75$9.25$2.95$11.75$1.50$8.99$1.09$11.25$1.25$1.25$11.25$11.75$2.15$8.99$1.69$11.75$6.49$8.75$9.25$11.25$4.45$1.25$11.25$4.45$8.49$8.99$8.49$8.99$11.25$1.25$11.75$1.25$11.75$9.25$4.45$11.25$2.15$32.94$32.94$32.94$1.25$11.25$11.48$1.69$1.09$17.50$17.50$4.45$6.49$9.25$8.75$9.25$9.25$8.75$8.75$2.15$2.95$17.50$17.50$10.98$11.48$11.48$3.39$8.99$1.69$8.99$1.09$10.98$3.39$8.99$1.09$9.25$8.75$11.25$4.45$2.95$9.25$22.20$22.20$22.20$8.49$8.99$8.75$8.75$11.75$8.75$11.25$9.25$11.25$11.25$8.75$11.25$2.95$1.25$8.49$1.69$11.75$11.25$8.75$8.75$4.45$8.49$3.99$8.49$3.99$11.48$1.69$1.09$11.25$1.50$10.58$1.69$9.25$11.25$8.75$9.25$11.25$11.25$8.75$11.75$8.75$8.75$8.75$2.15$11.25$11.75$2.50$2.50$4.45$9.25$4.45$11.25$8.49$3.99$9.25$9.25$11.25$9.25$11.75$11.25$1.25$23.50$23.50$1.25$8.99$8.49$7.40$7.40$8.75$1.25$4.45$8.75$2.15$8.75$4.45$7.40$7.40$7.40$8.99$3.99$8.99$1.69$8.75$8.75$8.75$8.75$11.25$11.25$2.95$8.75$18.50$18.50$8.49$3.99$2.95$9.25$9.25$3.00$3.00$1.25$8.75$9.25$4.45$8.75$11.25$4.45$10.98$22.16$22.16$4.45$8.75$9.25$6.49$9.25$11.25$8.75$9.25$2.15$9.25$4.45$9.25$2.95$9.25$8.75$9.25$1.25$1.25$8.75$8.75$9.25$4.45$11.75$11.75$11.75$9.25$9.25$16.98$16.98$2.39$3.39$3.39$9.25$11.75$11.25$2.15$8.75$9.25$4.45$10.98$11.25$9.25$22.50$22.50$9.25$2.95$1.50$11.48$8.49$1.69$8.49$8.49$8.49$6.78$6.78$11.75$4.45$8.75$4.45$11.89$9.39$8.75$2.95$1.25$9.25$8.75$23.78$23.78$8.75$9.25$2.15$2.15$1.25$8.49$3.99$10.98$1.09$8.75$4.45$8.75$11.75$2.95$4.45$9.25$8.75$8.49$3.99$22.50$22.50$11.25$1.25$8.75$8.75$18.50$18.50$6.49$8.75$8.75$4.45$8.49$3.99$8.99$1.09$8.49$2.39$11.48$1.69$2.50$2.50$9.25$1.50$17.50$17.50$2.95$8.75$4.45$11.75$8.75$8.49$1.69$8.49$3.99$8.99$8.99$3.99$8.99$11.25$4.45$1.25$3.99$10.98$7.40$3.00$7.40$4.00$8.49$3.99$9.25$4.45$11.25$1.25$11.75$1.25$11.25$2.15$11.25$4.45$3.75$3.75$3.75$11.75$8.99$2.39$8.75$4.45$1.25$8.99$8.49$2.18$2.18$8.49$2.18$2.18$1.09$8.75$2.95$1.25$1.50$11.25$9.25$2.95$1.25$8.49$3.99$11.48$3.99$8.49$11.25$1.25$8.99$1.69$11.25$1.25$6.49$8.75$9.25$8.75$2.95$8.75$11.75$8.69$8.69$2.29$3.99$8.49$8.75$8.75$1.25$11.75$11.25$11.25$11.25$1.25$9.25$11.75$6.49$3.99$8.49$11.25$2.15$11.25$11.89$8.99$1.69$8.99$8.99$3.99$8.99$9.25$9.25$2.15$7.40$7.40$8.75$8.75$9.25$4.45$11.25$1.25$11.75$11.25$1.25$3.99$8.49$8.49$8.49$8.99$8.75$2.15$1.25$8.49$1.09$1.09$8.75$2.95$1.25$9.25$1.25$2.15$11.25$1.25$4.45$8.75$2.50$2.50$8.90$8.90$8.75$8.75$8.75$11.25$11.25$10.98$3.99$10.98$3.99$1.69$8.99$9.25$8.75$8.99$1.09$9.25$2.95$8.75$9.25$3.99$8.49$8.75$8.75$22.50$22.50$10.98$3.27$3.27$3.27$3.99$8.99$1.09$11.08$8.75$4.45$11.08$3.99$8.49$4.30$4.30$9.25$8.75$11.25$11.25$9.25$8.49$8.99$8.49$8.75$2.95$4.45$9.25$2.95$9.25$8.75$11.25$4.45$16.98$16.98$8.49$2.39$11.25$3.75$3.75$3.75$9.25$4.45$9.25$9.25$4.45$8.75$9.25$8.75$9.25$9.25$9.25$11.48$8.99$22.50$22.50$11.75$11.25$1.25$8.75$2.15$1.25$11.25$8.75$1.25$11.25$1.50$11.25$11.25$9.25$6.49$8.90$8.90$8.75$4.45$11.25$1.25$17.50$17.50$9.25$8.75$11.75$3.00$3.00$8.49$8.49$10.98$8.99$3.99$8.75$4.45$8.99$1.69$11.75$8.75$11.25$4.45$11.75$1.25$11.75$2.95$8.99$8.99$2.18$2.18$17.98$17.98$8.99$8.49$1.69$11.75$11.25$2.95$3.75$3.75$3.75$9.25$11.75$8.75$2.15$1.50$8.49$8.49$3.39$8.69$3.89$8.75$4.45$8.75$11.25$2.15$8.75$8.49$1.69$8.49$8.49$1.25$8.75$11.75$11.75$8.99$1.09$8.75$4.45$8.75$2.95$8.75$2.15$3.99$8.49$8.99$3.99$8.49$1.69$1.09$8.99$1.09$9.25$8.75$8.99$2.39$1.25$1.25$11.25$11.25$9.25$9.25$11.25$1.50$3.99$8.49$11.25$9.25$11.25$17.50$17.50$8.75$8.90$8.90$8.75$8.75$8.99$2.39$11.25$9.25$2.15$11.25$1.25$11.75$1.25$11.25$11.75$1.25$11.25$11.25$8.49$10.98$8.75$1.25$8.75$8.49$8.49$1.50$1.50$8.75$4.45$11.25$1.25$11.75$8.49$2.39$9.25$4.45$9.25$8.75$8.99$1.69$17.50$17.50$2.39$8.99$8.99$11.25$4.45$8.75$4.45$9.25$6.49$10.98$8.49$8.49$1.09$1.69$9.25$4.45$8.75$1.25$2.95$3.99$8.49$11.75$11.75$2.15$11.48$8.75$2.15$1.25$11.25$2.15$1.25$8.75$8.75$6.49$1.69$8.99$8.75$11.75$10.98$1.09$8.49$3.39$8.75$2.15$1.25$11.48$10.98$10.98$8.49$2.95$9.25$9.25$11.75$4.45$11.48$11.25$8.75$4.45$1.69$8.99$8.75$4.45$1.50$11.75$2.15$8.99$2.39$8.75$2.95$1.25$8.75$2.15$1.25$2.18$2.18$2.18$2.18$11.48$8.75$2.95$11.75$11.75$1.25$10.58$8.99$2.39$11.75$4.45$11.25$11.25$17.50$17.50$8.75$8.75$8.75$22.50$22.50$9.25$8.75$4.45$11.75$1.25$11.25$11.25$2.95$8.99$1.69$11.25$4.45$8.75$6.49$8.75$4.45$9.25$4.45$11.75$11.75$4.45$11.89$11.75$11.25$2.95$1.50$4.45$8.75$8.99$1.09$8.99$1.09$3.99$11.48$8.49$9.25$4.45$11.48$9.25$2.95$9.25$8.49$8.99$8.99$8.49$8.75$2.95$4.45$11.89$10.58$8.19$1.69$8.75$2.15$1.25$17.50$17.50$6.49$9.25$2.15$8.75$4.45$8.75$1.25$11.48$11.48$8.99$2.18$2.18$8.49$8.99$2.39$2.39$2.18$2.18$8.75$4.45$11.25$9.25$9.25$11.25$11.25$4.45$2.95$11.75$8.49$8.49$8.99$1.69$9.25$11.25$11.75$9.25$8.75$11.75$8.75$8.75$11.25$11.25$10.98$11.25$4.45$10.98$8.49$8.99$3.39$3.99$8.99$1.09$1.09$2.39$17.50$17.50$4.45$11.25$11.25$4.45$9.25$4.45$8.75$2.15$1.25$11.89$2.95$11.75$1.25$11.25$4.45$11.48$11.48$2.95$9.25$8.75$9.25$2.95$11.25$1.25$11.75$1.25$8.99$2.39$1.25$11.25$1.25$11.25$8.49$3.99$35.00$35.00$35.00$35.00$27.75$27.75$27.75$8.75$11.80$11.80$11.80$11.80$8.90$8.90$5.90$5.90$6.49$10.98$17.98$17.98$2.39$9.25$8.75$2.15$8.75$4.45$8.49$1.69$8.19$8.69$10.98$3.99$11.48$11.48$4.45$8.75$6.49$8.75$8.75$9.25$1.25$4.45$8.49$1.69$9.25$4.45$8.99$1.09$11.25$2.95$11.08$11.08$3.89$10.98$11.25$8.75$11.25$9.25$4.30$4.30$8.75$8.49$3.99$1.69$8.99$8.49$1.69$11.75$11.25$11.89$9.25$2.95$9.25$2.95$8.75$4.45$4.45$8.75$10.98$11.48$8.49$9.25$4.45$11.75$11.89$8.99$8.49$8.75$9.25$8.75$8.75$11.75$11.75$4.45$11.25$11.75$2.50$2.50$8.99$1.69$11.75$2.15$1.25$9.25$8.75$8.90$8.90$9.25$2.95$8.75$11.25$8.90$8.90$11.25$11.75$11.48$1.69$3.39$9.25$2.95$8.99$1.69$8.49$10.98$11.25$2.95$8.99$1.69$8.75$2.15$1.25$8.75$2.95$9.25$2.50$2.50$11.25$1.25$11.75$2.50$2.50$11.25$1.50$8.75$1.25$2.95$11.48$11.48$8.75$8.75$2.15$11.75$1.25$9.25$9.25$6.49$11.75$8.49$8.49$1.09$10.98$8.75$1.25$2.15$11.25$1.50$11.25$11.25$8.49$8.49$8.75$1.50$1.25$1.50$8.75$2.50$2.50$2.15$7.40$7.40$4.00$9.25$9.39$9.25$9.25$9.39$11.25$8.90$8.90$11.25$6.00$6.00$6.00$6.00$11.25$11.25$11.25$22.50$22.50$11.48$1.09$8.49$8.49$17.50$17.50$11.25$1.50$9.25$8.75$3.99$8.49$8.75$8.75$8.75$8.75$8.75$11.75$1.50$11.25$11.25$2.95$8.99$10.98$9.25$8.75$4.45$8.49$1.09$2.39$8.75$8.75$11.48$8.99$8.49$8.49$2.39$10.98$8.49$3.99$11.75$4.45$8.75$2.15$1.25$10.98$8.99$11.25$1.50$8.75$2.15$1.25$8.75$9.25$8.75$11.25$1.50$8.75$1.25$4.45$10.98$8.75$2.95$1.25$8.75$2.95$1.25$8.49$8.49$2.39$11.25$1.25$8.75$8.75$9.25$8.75$11.89$1.25$8.75$2.15$1.25$8.99$1.09$8.75$4.45$26.25$26.25$26.25$8.75$4.45$11.75$2.95$8.75$8.75$11.75$8.75$11.25$11.25$11.25$4.45$1.25$8.49$8.49$8.49$8.99$8.99$2.39$2.39$3.99$8.75$4.45$2.15$9.25$1.25$11.25$11.75$8.75$4.45$11.25$2.15$8.75$4.45$8.75$8.75$1.25$11.25$2.15$8.75$5.90$5.90$11.75$1.25$9.25$3.75$3.75$3.75$8.75$1.25$4.45$11.75$4.45$8.75$23.50$23.50$8.75$2.95$8.75$8.75$11.89$4.45$2.95$1.25$8.75$4.45$2.95$1.25$8.75$2.15$1.25$11.75$2.95$8.99$3.39$9.25$9.25$17.50$17.50$2.95$11.89$1.50$11.25$2.95$9.25$11.25$11.25$2.95$8.75$9.25$4.30$4.30$8.75$8.75$11.25$8.75$4.30$4.30$8.75$1.25$2.15$8.49$8.49$3.39$3.39$10.98$10.98$2.39$11.25$11.75$11.75$1.25$5.90$5.90$8.75$11.25$9.25$4.45$1.50$3.39$8.99$2.39$11.25$2.15$11.25$11.75$11.75$4.45$11.75$4.45$9.25$8.75$8.49$8.99$8.49$8.99$11.75$8.75$8.49$3.99$3.89$11.08$8.49$8.99$8.49$8.49$8.49$11.25$2.15$17.50$17.50$8.75$2.95$8.49$8.49$10.98$1.09$11.25$2.15$2.95$1.25$8.75$9.25$9.25$9.25$2.95$8.75$2.15$1.25$8.99$3.99$11.75$2.15$8.99$3.39$9.25$8.75$11.25$11.25$4.45$8.75$2.15$1.25$11.75$4.45$9.25$2.95$8.49$8.49$11.25$8.75$4.45$11.25$11.25$11.25$11.25$4.45$8.49$1.69$8.49$3.39$8.75$11.25$9.25$8.75$11.25$11.25$11.75$11.25$11.75$11.25$11.75$21.96$21.96$10.98$1.69$11.48$8.99$8.49$1.69$9.25$2.15$1.50$11.25$1.50$8.75$8.75$2.95$8.49$1.69$8.75$2.95$1.25$11.25$2.15$11.08$8.49$8.49$8.49$11.75$1.25$11.75$8.75$8.75$8.75$4.45$11.25$1.50$23.50$23.50$11.75$6.49$8.75$4.45$6.49$8.75$2.50$2.50$2.15$8.49$2.39$8.75$11.75$4.45$8.99$10.98$9.25$2.95$9.25$9.25$11.75$8.75$8.75$8.75$10.98$11.25$9.25$8.75$8.75$2.15$11.25$2.15$4.45$11.75$8.49$2.39$9.25$1.25$1.25$1.25$1.25$8.75$2.15$8.49$1.69$11.25$1.50$8.75$8.75$8.49$3.99$8.99$1.09$11.25$1.25$8.49$2.39$8.49$8.75$9.25$11.25$4.45$11.25$11.89$8.99$8.49$8.75$4.45$8.75$11.75$11.75$8.90$8.90$9.39$2.95$8.49$3.99$8.75$2.15$1.25$21.96$21.96$8.49$1.69$8.75$4.45$8.49$8.99$8.49$3.99$8.75$8.75$2.95$8.75$17.50$17.50$9.25$2.95$8.75$6.49$4.30$4.30$8.75$8.75$2.15$1.50$8.49$8.49$2.39$9.25$4.45$6.49$11.75$4.45$10.98$1.69$9.39$9.25$9.25$2.95$8.75$2.15$1.25$11.25$9.25$8.75$11.25$8.75$11.25$2.50$2.50$2.50$2.50$6.00$6.00$6.00$6.00$8.90$8.90$5.90$5.90$11.25$11.25$8.49$10.98$8.75$2.15$1.50$9.25$1.25$1.50$2.15$1.25$8.75$2.95$8.49$3.99$11.25$4.30$4.30$11.75$2.15$18.50$18.50$8.49$2.39$8.75$4.45$11.75$8.99$3.99$9.25$9.25$1.50$8.75$2.95$6.49$11.75$8.49$8.99$8.75$4.45$6.49$22.50$22.50$9.25$2.95$8.49$1.69$10.98$8.75$4.45$11.25$2.95$8.99$8.49$2.39$11.75$6.49$11.25$11.75$2.95$8.99$1.69$8.99$2.18$2.18$1.09$8.99$8.99$1.09$8.99$8.99$8.49$10.98$1.09$11.75$9.25$11.25$11.25$2.15$11.25$8.75$4.45$2.95$11.75$1.50$8.99$10.98$2.39$8.75$2.15$9.25$1.50$8.75$2.15$3.99$8.99$6.49$8.75$8.90$8.90$8.99$3.99$17.50$17.50$11.25$1.25$10.98$9.25$4.45$1.25$3.00$3.00$11.25$4.45$4.45$2.95$9.25$11.25$2.15$11.25$11.25$4.45$2.95$9.25$11.25$1.25$8.75$2.95$1.25$8.75$4.45$11.48$11.48$8.49$2.39$11.25$11.75$2.15$1.50$2.15$8.75$11.25$8.90$8.90$11.25$11.25$1.25$4.45$9.25$9.25$8.75$9.25$8.75$8.75$9.25$8.75$11.75$11.75$8.75$8.75$8.90$8.90$2.95$10.98$8.49$8.49$10.98$8.99$8.99$11.75$17.50$17.50$11.75$3.99$8.49$10.98$1.69$17.50$17.50$8.99$2.39$8.99$2.39$1.25$8.75$2.95$11.75$11.25$17.50$17.50$8.49$8.49$2.39$11.25$1.50$8.75$3.00$3.00$1.25$8.75$4.45$11.75$11.75$4.45$21.96$21.96$8.75$4.45$8.75$11.25$9.25$8.99$2.39$9.25$8.75$10.98$8.49$3.99$3.39$11.75$1.50$4.45$9.25$8.75$1.25$11.75$8.75$1.50$8.75$8.75$2.15$1.50$8.75$2.95$8.75$8.75$17.50$17.50$8.75$6.49$4.45$11.25$11.25$4.30$4.30$8.75$11.25$4.45$8.99$2.39$9.25$9.25$9.25$4.45$11.75$11.25$2.95$2.15$11.25$11.25$8.75$2.15$1.50$9.25$4.45$10.98$8.99$2.18$2.18$8.75$4.45$1.25$8.99$2.39$4.45$8.75$10.98$11.75$1.50$10.98$8.99$8.49$3.99$8.99$8.49$3.99$8.49$8.49$8.99$11.25$11.25$10.98$10.98$10.98$2.39$3.39$8.75$1.25$2.95$11.75$1.50$10.98$1.69$4.45$8.75$8.75$8.75$8.75$4.45$9.25$8.75$11.25$8.75$3.99$8.99$8.49$11.25$11.25$8.75$4.45$8.75$4.45$1.25$8.75$8.75$1.50$2.15$11.75$11.75$11.75$11.75$11.75$1.50$8.75$9.25$1.25$8.75$2.15$8.99$1.09$4.45$11.25$11.75$2.15$8.75$8.75$1.25$9.25$2.15$11.75$11.25$8.75$11.25$4.45$8.49$1.69$8.75$8.75$8.99$8.49$9.25$11.25$2.95$4.45$11.75$6.49$11.48$8.99$4.36$4.36$4.36$4.36$11.48$8.99$8.49$11.48$8.75$2.15$1.50$8.99$1.69$11.25$1.25$9.25$9.25$8.75$9.25$8.90$8.90$2.15$9.25$10.98$8.49$8.75$9.25$4.30$4.30$9.25$8.75$8.75$2.15$1.25$8.75$1.25$8.75$5.90$5.90$9.25$8.75$9.25$4.45$9.25$11.75$2.50$2.50$9.25$2.15$9.25$1.50$1.25$11.25$2.95$8.75$8.75$8.75$10.98$8.75$8.75$8.75$2.15$1.25$10.98$8.75$2.15$1.50$8.75$2.95$1.25$9.25$9.25$8.49$2.39$8.75$4.45$9.25$8.75$8.75$8.75$9.25$8.75$9.25$8.75$8.75$8.75$8.75$9.25$8.75$9.25$8.75$9.25$8.75$8.75$8.75$9.25$8.75$9.25$8.75$8.99$8.99$8.75$2.95$1.25$11.75$1.50$11.25$11.25$8.75$1.50$2.15$16.98$16.98$11.75$1.50$8.75$4.30$4.30$1.50$8.75$2.95$1.25$1.25$9.25$4.45$11.25$8.75$4.45$8.75$2.15$1.25$10.98$1.69$8.75$1.25$8.75$1.25$11.25$8.75$8.75$8.49$1.69$9.25$11.75$8.49$2.39$9.25$2.95$6.49$8.75$8.75$9.25$8.75$6.78$6.78$17.98$17.98$3.39$11.75$11.25$8.75$4.45$11.75$9.25$8.75$6.49$8.99$2.39$8.75$11.25$11.75$4.45$8.75$2.15$9.25$9.25$9.25$11.89$11.75$11.25$9.25$9.25$8.75$8.75$8.49$1.69$1.09$11.25$1.50$11.25$11.25$11.75$1.50$8.49$8.99$22.50$22.50$8.75$4.30$4.30$8.75$11.25$2.15$11.25$2.95$4.45$11.25$8.49$3.39$2.39$11.75$2.15$11.75$8.99$2.39$8.75$11.75$11.89$1.25$7.50$7.50$7.50$7.50$7.50$11.89$1.09$8.49$2.39$8.75$8.75$8.75$8.75$9.25$11.25$8.75$8.90$8.90$9.25$8.75$8.75$11.75$3.00$3.00$1.50$11.25$11.75$8.99$10.98$4.45$8.75$2.15$9.25$11.25$4.45$1.69$10.98$9.25$11.75$9.25$4.45$10.98$3.99$8.49$1.25$9.25$4.45$10.98$8.75$8.75$11.75$11.25$8.49$11.48$4.45$1.25$11.25$8.99$1.09$2.39$11.25$2.15$8.75$4.45$8.49$1.69$10.98$1.69$9.25$4.45$11.25$8.75$11.25$11.75$11.25$22.50$22.50$8.49$2.39$2.50$2.50$8.75$8.75$9.25$9.25$11.25$8.99$1.09$8.99$1.69$11.75$1.25$21.96$21.96$8.75$2.15$1.25$8.75$11.25$9.25$11.25$8.75$8.75$11.25$2.15$8.99$1.09$1.69$8.75$2.15$1.25$8.49$1.09$1.09$1.69$11.48$8.49$8.49$4.78$4.78$9.25$1.25$1.25$1.25$11.25$11.25$11.75$4.45$11.25$4.45$8.99$1.09$11.25$2.15$11.25$9.25$11.75$11.25$11.25$9.25$2.95$11.25$4.45$8.75$2.95$2.95$11.25$1.50$10.98$16.98$16.98$18.50$18.50$10.98$3.99$1.09$9.25$9.25$8.75$4.45$17.50$17.50$8.75$4.45$8.75$1.25$4.45$9.25$8.75$8.75$17.50$17.50$4.45$9.39$1.25$2.95$11.25$8.75$8.75$11.25$2.15$8.90$8.90$11.25$11.89$10.98$11.25$4.45$11.25$11.25$8.49$10.98$8.49$3.39$9.25$8.75$2.95$3.00$3.00$9.39$11.75$2.95$1.50$11.25$11.75$8.75$2.15$1.50$8.49$3.39$11.75$1.25$17.50$17.50$11.25$1.25$8.75$2.95$1.25$11.25$11.75$13.35$13.35$13.35$11.25$11.75$11.25$11.25$4.45$11.25$8.49$3.39$9.25$2.95$4.78$4.78$2.39$3.99$8.99$8.99$11.25$11.25$8.75$11.25$2.95$4.45$9.25$8.75$4.45$8.49$8.49$10.98$10.98$3.99$11.75$8.75$11.75$4.45$1.50$1.25$8.49$8.49$8.75$8.75$8.75$9.25$8.75$2.95$1.25$11.25$1.50$11.25$4.45$9.25$8.75$8.75$9.25$8.75$4.45$1.50$8.75$8.75$8.49$1.69$8.75$2.15$9.25$2.15$1.50$11.25$11.75$2.15$6.49$9.25$9.25$11.25$11.25$11.75$11.75$11.75$11.25$8.75$2.15$1.25$11.75$9.25$11.25$8.75$5.90$5.90$8.75$4.45$9.25$9.25$4.45$11.25$4.45$11.25$8.75$2.15$11.89$11.25$8.75$2.95$1.50$8.75$4.30$4.30$8.75$11.25$11.75$11.75$2.15$11.25$8.99$1.09$8.49$8.49$8.49$3.39$8.99$10.98$3.99$11.75$2.15$8.75$4.45$2.50$2.50$11.48$1.09$8.49$8.49$16.98$16.98$3.99$10.98$1.09$8.75$2.95$8.75$8.75$2.95$9.25$11.25$2.15$9.25$4.45$4.45$9.25$11.75$11.75$2.15$9.25$8.75$11.25$6.49$8.75$11.25$2.95$10.98$3.99$1.50$9.25$2.15$8.75$11.25$11.89$4.45$1.50$1.25$8.75$8.75$4.45$11.25$11.75$8.49$1.09$1.09$1.69$8.99$3.39$8.99$1.69$8.49$8.99$3.27$3.27$3.27$8.99$8.99$1.09$10.98$1.69$3.99$8.49$1.09$8.75$8.75$11.75$8.75$9.25$8.75$3.39$8.99$8.99$2.39$9.25$8.75$9.25$9.25$8.99$3.99$2.39$8.49$1.09$8.49$8.99$3.39$11.25$1.25$8.99$3.99$8.75$8.90$8.90$6.49$8.75$9.25$11.25$11.25$11.25$1.25$8.75$9.25$4.45$1.25$8.75$1.25$2.15$17.98$17.98$8.99$8.75$2.95$1.25$11.75$1.50$1.50$8.75$8.75$11.08$8.99$1.69$8.99$1.69$10.98$3.99$3.39$11.75$2.15$11.75$2.95$8.75$8.75$11.75$11.25$11.75$11.25$4.45$11.25$1.25$2.18$2.18$2.18$2.18$2.39$8.49$8.99$2.39$11.25$8.75$11.75$11.75$11.25$4.45$2.15$8.19$10.58$4.45$9.25$1.09$8.99$11.25$1.50$8.99$3.99$4.45$11.75$2.15$11.25$8.75$4.45$8.75$9.25$6.45$6.45$6.45$8.75$11.25$11.25$8.75$11.75$21.96$21.96$8.99$5.07$5.07$5.07$8.49$9.25$11.25$4.45$3.39$8.49$8.99$8.49$17.50$17.50$22.96$22.96$8.75$11.25$11.89$11.25$8.49$1.69$1.09$8.99$8.99$9.25$8.75$9.25$2.95$8.49$3.99$8.99$8.49$7.17$7.17$7.17$8.49$8.99$17.50$17.50$9.25$9.25$11.25$1.25$8.99$1.09$8.75$4.45$11.25$2.15$11.75$11.25$11.25$8.75$8.75$4.45$1.25$11.75$11.75$2.50$2.50$8.49$8.99$2.18$2.18$11.25$4.45$11.25$11.75$8.49$8.99$1.69$1.09$8.99$8.99$11.25$6.49$11.25$8.75$4.45$8.99$1.69$11.48$11.75$2.50$2.50$8.49$1.09$1.09$1.69$8.49$2.39$11.75$1.25$8.49$1.69$8.49$1.69$11.75$4.45$8.75$8.75$4.45$8.75$11.25$11.25$8.75$7.98$7.98$8.49$1.09$8.49$3.99$8.49$3.99$8.99$3.99$11.25$4.45$8.49$2.39$8.49$2.39$3.99$8.49$1.25$11.25$4.45$9.25$4.45$1.09$8.99$3.99$11.25$8.90$8.90$9.25$11.25$8.75$11.25$11.25$11.25$11.25$11.25$8.99$8.49$8.75$8.75$4.45$16.98$16.98$11.75$11.25$9.25$4.45$9.25$2.95$8.49$1.69$3.75$3.75$3.75$4.45$9.25$1.50$11.25$11.48$11.25$2.15$8.75$9.39$8.49$3.99$8.19$2.29$11.48$1.69$11.48$3.99$8.49$1.69$9.25$2.95$8.49$1.69$11.25$4.45$9.39$9.25$8.75$8.75$4.45$11.89$4.45$4.45$8.75$8.75$8.75$2.15$8.75$3.75$3.75$3.75$9.25$11.25$4.45$6.49$16.98$16.98$18.50$18.50$2.50$2.50$2.95$3.99$8.49$8.19$11.08$6.49$11.75$2.39$8.99$1.09$11.25$4.45$11.25$8.99$1.69$21.96$21.96$2.18$2.18$8.99$8.99$2.39$8.69$1.69$8.90$8.90$2.50$2.50$8.75$8.99$1.09$8.49$8.49$8.75$4.45$17.50$17.50$8.75$9.25$8.49$2.39$8.75$4.45$11.25$11.25$11.75$8.75$8.49$8.49$8.49$8.99$8.75$4.45$11.48$8.75$1.25$2.15$9.25$4.45$11.75$2.15$11.25$8.99$2.39$8.69$8.69$11.75$2.95$11.75$1.50$9.25$4.45$1.50$11.48$8.99$2.39$11.25$11.89$2.15$1.25$11.75$4.45$8.75$8.75$11.25$4.45$11.25$2.15$4.45$8.49$1.09$3.99$11.25$11.25$8.49$2.39$8.99$2.39$11.25$2.15$8.75$2.95$1.25$8.75$11.25$17.50$17.50$11.75$11.75$11.25$11.25$4.45$2.50$2.50$8.75$8.99$8.99$1.69$8.99$1.69$11.25$1.25$11.08$8.69$8.99$1.09$11.25$11.25$2.95$1.25$8.75$1.25$8.75$8.75$2.15$1.25$8.49$3.99$8.49$2.39$8.49$7.17$7.17$7.17$8.75$4.45$11.48$8.75$8.75$11.48$8.75$9.25$8.49$3.99$1.50$11.25$11.25$8.75$8.75$4.45$9.25$4.45$8.75$8.75$4.30$4.30$2.95$8.75$4.50$4.50$4.50$9.25$11.25$4.45$11.25$11.25$8.75$9.25$8.75$2.15$1.25$8.75$2.15$1.25$8.99$8.49$8.75$8.75$1.25$11.75$4.50$4.50$4.50$8.75$8.75$3.99$3.39$8.49$2.39$8.99$1.50$11.25$11.25$8.75$8.75$2.15$8.75$2.15$1.25$21.96$21.96$8.49$1.69$26.07$26.07$26.07$11.75$1.50$8.99$8.99$11.48$9.25$9.25$8.75$8.75$8.75$9.25$8.75$8.75$2.15$1.25$11.89$8.75$11.75$4.45$18.50$18.50$9.25$9.39$8.49$2.39$8.49$1.69$1.09$8.99$8.49$2.18$2.18$11.25$1.25$8.49$3.39$8.49$3.99$11.25$8.75$8.49$1.69$16.98$16.98$9.25$9.25$11.75$1.25$11.25$8.75$8.49$8.49$8.75$1.25$1.25$1.25$11.25$12.98$12.98$11.75$11.75$4.45$11.25$11.75$10.98$8.49$8.49$2.39$9.25$11.25$8.75$2.95$1.50$11.25$2.95$9.25$2.95$9.25$8.75$11.25$8.75$8.75$4.45$11.25$1.25$8.75$2.95$2.50$2.50$9.25$9.25$9.25$6.49$17.50$17.50$8.49$1.69$8.49$3.99$8.75$2.95$2.95$8.49$8.99$8.99$1.09$8.75$4.45$1.25$11.25$11.75$11.25$9.25$11.25$1.50$11.25$2.15$10.98$8.75$11.75$2.95$11.25$11.25$9.25$8.75$9.25$8.75$8.75$8.75$1.25$11.25$1.50$2.15$8.75$8.75$11.25$8.75$8.75$11.25$4.45$8.49$8.49$8.49$8.49$8.99$1.69$2.39$1.09$1.09$11.25$2.95$35.25$35.25$35.25$8.75$2.95$1.25$11.25$2.15$9.25$4.45$8.75$8.75$8.75$4.45$1.25$11.89$8.75$2.15$1.25$8.49$1.09$1.09$1.69$8.69$8.69$9.25$2.95$10.98$2.39$22.50$22.50$21.96$21.96$10.98$8.49$1.69$11.75$2.95$8.75$11.25$8.75$9.25$8.75$8.19$10.58$8.75$2.95$1.50$2.50$2.50$9.25$4.45$9.25$11.25$8.69$8.69$3.89$8.69$1.69$4.45$9.25$11.25$4.45$2.15$8.19$8.69$4.45$11.25$1.25$11.25$8.75$11.89$11.75$11.75$9.25$8.75$2.15$1.50$11.75$4.45$3.99$8.99$10.98$2.39$1.25$2.95$8.75$2.95$9.25$9.25$9.25$8.75$2.15$9.25$9.25$3.39$8.49$8.49$2.39$10.98$

### Step 15. How many orders were made in the period?

In [19]:
#df.order_id.unique()
o = df.order_id.nunique()
o
#df.order_id.count()

1834

### Step 16. What is the average revenue amount per order?

In [28]:
avg = r/o
avg

TypeError: unsupported operand type(s) for /: 'str' and 'int'

### Step 17. How many different items are sold?

In [24]:
df.order_id.nunique()

1834

In [25]:
df.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [ ]:
df.tail()

In [ ]:
df.columns

In [ ]:
top_items = df.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(10)
top_items

In [ ]:
top_items = df.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(10)

plt.bar(top_items.index, top_items.values)
plt.title("Top 10 Items by Quantity")
plt.xlabel("Item Name")
plt.ylabel("Quantity")
plt.xticks(rotation=90)
plt.show()

In [ ]:
plt.scatter(df['quantity'], df['item_price'])
plt.title("Quantity vs Item Price")
plt.xlabel("Quantity")
plt.ylabel("Item Price")
plt.show()

In [27]:
corr = df[['order_id', 'quantity', 'item_price']].corr()

plt.imshow(corr)
plt.title("Correlation Matrix")
plt.colorbar()
plt.xticks(range(len(corr.columns)), corr.columns)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.show()

ValueError: could not convert string to float: '$2.39'

In [ ]:
top5 = df.groupby('item_name')['quantity'].sum().sort_values(ascending=False).head(5)

plt.pie(top5.values, labels=top5.index, autopct='%1.1f%%')
plt.title("Top 5 Items Quantity Share")
plt.show()

In [ ]:
stats = df.groupby('quantity')['item_price'].agg(['mean', 'std']).head(10)

plt.errorbar(stats.index, stats['mean'], yerr=stats['std'], fmt='o')
plt.title("Mean Item Price with Error Bar")
plt.xlabel("Quantity")
plt.ylabel("Mean Price")
plt.show()

In [ ]:
plt.boxplot(df['item_price'])
plt.title("Boxplot of Item Price")
plt.ylabel("Item Price")
plt.show()