### *Data Preprocessing:(StudentPerformaceFactors)*

## *import data*

In [30]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv(r"C:\Users\Asus\OneDrive\Apps\Desktop\vikashsir\StudentPerformanceFactors.csv")
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8.0,98,Medium,Yes,1.0,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6.0,65,Medium,Yes,3.0,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7.0,76,Medium,Yes,1.0,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,NaN,81,Medium,Yes,3.0,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6.0,65,Low,Yes,3.0,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6.0,91,High,Yes,2.0,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9.0,94,Medium,Yes,0.0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [5]:
df.head(5)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7.0,79,Low,Yes,0.0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8.0,56,Low,Yes,2.0,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7.0,91,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8.0,98,Medium,Yes,1.0,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6.0,65,Medium,Yes,3.0,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [7]:
df.tail(5)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
6602,25,69,High,Medium,No,7.0,76,Medium,Yes,1.0,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,NaN,81,Medium,Yes,3.0,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6.0,65,Low,Yes,3.0,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6.0,91,High,Yes,2.0,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9.0,94,Medium,Yes,0.0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

### *Q.1 Display column names &amp; Datatype of each column?*

In [55]:
df.dtypes

Hours_Studied                   int64
Attendance                      int64
Parental_Involvement           object
Access_to_Resources            object
Extracurricular_Activities     object
Sleep_Hours                   float64
Previous_Scores                 int64
Motivation_Level               object
Internet_Access                object
Tutoring_Sessions             float64
Family_Income                  object
Teacher_Quality                object
School_Type                    object
Peer_Influence                 object
Physical_Activity               int64
Learning_Disabilities          object
Parental_Education_Level       object
Distance_from_Home             object
Gender                         object
Exam_Score                      int64
dtype: object

### *Q.2 Display total no of rows &amp; columns?*

In [17]:
df.shape

(6607, 20)

### *Q.3 Display only the name of columns?*

In [35]:
df.columns.tolist()

['Hours_Studied',
 'Attendance',
 'Parental_Involvement',
 'Access_to_Resources',
 'Extracurricular_Activities',
 'Sleep_Hours',
 'Previous_Scores',
 'Motivation_Level',
 'Internet_Access',
 'Tutoring_Sessions',
 'Family_Income',
 'Teacher_Quality',
 'School_Type',
 'Peer_Influence',
 'Physical_Activity',
 'Learning_Disabilities',
 'Parental_Education_Level',
 'Distance_from_Home',
 'Gender',
 'Exam_Score']

### *Q.4 Display the name of those columns which is having object data type?*

In [46]:
df.select_dtypes(include='object').columns.tolist()

['Parental_Involvement',
 'Access_to_Resources',
 'Extracurricular_Activities',
 'Motivation_Level',
 'Internet_Access',
 'Family_Income',
 'Teacher_Quality',
 'School_Type',
 'Peer_Influence',
 'Learning_Disabilities',
 'Parental_Education_Level',
 'Distance_from_Home',
 'Gender']

### *Q.5 Display Unique value of each column?*

In [47]:
df.nunique()

Hours_Studied                 41
Attendance                    41
Parental_Involvement           3
Access_to_Resources            3
Extracurricular_Activities     2
Sleep_Hours                    7
Previous_Scores               51
Motivation_Level               3
Internet_Access                2
Tutoring_Sessions              9
Family_Income                  3
Teacher_Quality                3
School_Type                    2
Peer_Influence                 3
Physical_Activity              7
Learning_Disabilities          2
Parental_Education_Level       3
Distance_from_Home             3
Gender                         2
Exam_Score                    45
dtype: int64

### *Q.6 Diplay first 10 Unique value of a particular column?*

Hours_Studied                  6
Attendance                     8
Parental_Involvement           2
Access_to_Resources            3
Extracurricular_Activities     2
Sleep_Hours                    3
Previous_Scores               10
Motivation_Level               3
Internet_Access                1
Tutoring_Sessions              4
Family_Income                  3
Teacher_Quality                3
School_Type                    2
Peer_Influence                 3
Physical_Activity              5
Learning_Disabilities          1
Parental_Education_Level       3
Distance_from_Home             3
Gender                         2
Exam_Score                     8
dtype: int64

### *Q.7 Check whether null value exist in a dataset?*

### *Q.8 Display counting of null values of each column?*

In [19]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                   13
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              3
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

### *Q.9 Display Total number of null values in a dataset?*

In [18]:
print(df.isnull().sum().sum())

251

### *Q.10 Display total % of null values in a dataset?*

In [53]:
(df.isnull().sum() / len(df) * 100)

Hours_Studied                 0.000000
Attendance                    0.000000
Parental_Involvement          0.000000
Access_to_Resources           0.000000
Extracurricular_Activities    0.000000
Sleep_Hours                   0.196761
Previous_Scores               0.000000
Motivation_Level              0.000000
Internet_Access               0.000000
Tutoring_Sessions             0.045406
Family_Income                 0.000000
Teacher_Quality               1.180566
School_Type                   0.000000
Peer_Influence                0.000000
Physical_Activity             0.000000
Learning_Disabilities         0.000000
Parental_Education_Level      1.362192
Distance_from_Home            1.014076
Gender                        0.000000
Exam_Score                    0.000000
dtype: float64

### *Q.11 Display mean,count,std,min,max of dataset?*

In [22]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6594.000000,6607.000000,6604.00000,6607.000000,6607.000000
mean,19.975329,79.977448,7.029421,75.070985,1.49364,2.967610,67.235659
std,5.990594,11.547475,1.468528,14.400397,1.23068,1.031231,3.890456
min,1.000000,60.000000,4.000000,50.000000,0.00000,0.000000,55.000000
25%,16.000000,70.000000,6.000000,63.000000,1.00000,2.000000,65.000000
50%,20.000000,80.000000,7.000000,75.000000,1.00000,3.000000,67.000000
75%,24.000000,90.000000,8.000000,88.000000,2.00000,4.000000,69.000000
max,44.000000,100.000000,10.000000,100.000000,8.00000,6.000000,101.000000

### *Q.12.Drop particular column from given dataset?*

### *Q.13 Convert null values with mean?*

In [25]:
print(df.isnull().sum().mean())

12.55

### *Q.14 Find the dimension of a dataset?*

### *Q.15 How nunique differ from unique?*